Repository SinergiaTIC/SinergiaDA, pull requests merged in 2025-03, with the labels that each got.

#290 Hotfix - API - Corregir error al crear fuente de datos MySQL
  eda/eda_api/lib/services/connection/db-systems/mysql-connection.ts
Labels: bug, SinergiaDA

#287 Hotfix - API - Deshacer filtrado por valores vacío en filtros de informe
  eda/eda_api/lib/services/query-builder/qb-systems/mySql-builder.service.ts
Labels: bug, EDA

#291 Enhancement - APP - Incluir mapas de capas en SinergiaDA
  eda/eda_app/src/app/module/pages/data-sources/data-source-detail/sda-data-source-detail.component.html
Labels: enhancement, SinergiaDA, Mapas

#307 Hotfix - APP - Traducir cadena del login
  eda/eda_app/src/locale/stic_messages.es.xlf
Labels: bug, SinergiaDA, Traducciones, General

#309 Hotfix - APP - Corrección de visibilidad de filtros en informes EDA y modo árbol.
  eda/eda_app/src/app/module/pages/dashboard/dashboard.component.ts
  eda/eda_app/src/app/module/pages/dashboard/global-filter/global-filter.component.html
Labels: bug, EDA, Filtros
